### ISSUE TITLE
Feature Request: Get a list of upgradable packages

### ISSUE THREAD

**Issue by Lockszmith-GH** [ethanbergstrom/Cobalt#10]
Running `winget upgrade` lists all the upgradable packages.

An `-Upgradable` switch for `Get-WinGetPackage` could make this available via Cobalt.

Is this something you can add?

**Comment by sibbl** [comment]
Would also love to see this feature. It would allow me to simply update all packages except some specific ones I can filter out.

Maybe `List-WinGetPackageUpdates` might be a good name instead of a switch?

**Comment by ethanbergstrom** [comment]
Can someone help me understand the use case for getting a list of 'upgradable' packages you feel comfortable having WinGet upgrade?

I was thinking that any package you feel comfortable having WinGet upgrade would have been a package originally installed by WinGet (as opposed to a package WinGet 'found' and the corresponding package may have questionable/inconsistent install/upgrade behavior), and if the goal is to automate everything, that you'd already have that comprehensive list of WinGet-installed packages stored somewhere. 

```powershell
@('package1','package2','etc...') | ForEach-Object { Update-WinGetPackage -ID $_ }
```

**Comment by Lockszmith-GH** [comment]
My specific need is based on what `winget` does natively, compared to what I can achieve with **Cobalt**.

The following code is what I came up with for identifying what might be upgradable, the logic is simple:
* get a list of package from winget (using `Get-WinGetPackage`)
* Check the available version for each package, and if different list it.
```ps1
Get-WinGetPackage | Where Source -eq winget | ForEach-Object {
         $local:i = Get-WinGetPackageInfo $_.Id;
         $i.ID = $_.Id;
         $i.VersionInstalled = $_.Version;
         $i.PSTypeName = "WinGetPackageszInfo"
         [PSCustomObject]$i
     } |
         Tee-Object -Variable InstalledPackagesCache |
         Where-Object { $_.VersionInstalled -ne $_.Version } |
         Format-Table -Property ID,Type,Moniker,Version,VersionInstalled,Description -Wrap -AutoSize
```

The problem with the code above:
* On my system right now, it runs for `1m 11s` - that's a long time.
* More importantly: it produces a completely bogus output, this is what I have right now:
```txt
ID                            Type     Moniker         Version         VersionInstalled Description                                                                                               

--                            ----     -------         -------         ---------------- -----------
Canonical.Ubuntu              msix     ubuntu          2004.2021.825.0 2004.2022.1.0    Ubuntu on Windows allows you to use Ubuntu Terminal and run Ubuntu command line utilities including bash, ssh, git, apt and many more. This is the latest     
                                                                                        LTS release.
Microsoft.Edge                wix      microsoft-edge  101.0.1210.32   101.0.1210.39    World-class performance with more privacy, more productivity, and more value while you browse.
Microsoft.EdgeWebView2Runtime exe      webview2        101.0.1210.32   101.0.1210.39    Embed web content (HTML, CSS, and JavaScript) in your native applications with Microsoft Edge WebView2.
NoMachine.NoMachine           inno     nomachine       7.7.4           7.9.2            Free remote desktop for everybody. This version contains both the server and the client side parts of the application.
RandomEngy.VidCoder           inno                     6.46            7.14.0           VidCoder is an open-source DVD/Blu-ray ripping and video transcoding application for Windows. It uses HandBrake as its encoding engine.
Waterfox.Waterfox             nullsoft waterfox        G4.1.2          4.1.2            Waterfox is free and open source browser, based on Mozilla Firefox.
voidtools.Everything.Lite     msi      everything-lite 1.4.1.1015      1.4.1015         Everything is search engine that locates files and folders by filename instantly for Windows. Unlike Windows search Everything initially displays every file  
                                                                                        and folder on your computer (hence the name Everything). You type in a search filter to limit what files and folders are displayed.
gerardog.gsudo                wix      gsudo           1.3.0           1.3.0.0          A Sudo for Windows - run elevated without spawning a new Console Host Window
AnyDeskSoftwareGmbH.AnyDesk   wix      anydesk         ad 7.0.7        7.0.7            Connect to a computer remotely, be it from the other end of the office or halfway around the world.
VideoLAN.VLC                  wix      vlc             3.0.17.4        3.0.17.0         VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various  
                                                                                        streaming protocols.
AmineMouafik.Ferdi            wix                      5.8.1           5.8.1.0          Ferdi is a desktop app that helps you organize how you use your favourite apps by combining them into one application. It is based on Franz - a software      
                                                                                        already used by thousands of people - with the difference that Ferdi gives you many additional features and doesn't restrict its usage! Ferdi is compatible   
                                                                                        with your existing Franz account so you can continue right where you left off. Find out more about Ferdi and its features on getferdi.com.
```

Why do I say it's ***bogus***?
This is the output of `winget upgrade` which return after **2 seconds**:
```txt
Name             Id           Version  Available Source
-------------------------------------------------------
VLC media player VideoLAN.VLC 3.0.17.0 3.0.17.4  winget
1 upgrades available.
```

While VLC should be excluded as well, the result came back after 2 seconds, which is over 1m faster then querying the packages one at a time.

As for what I plan to do with it?

* Getting a scheduled task periodically checking for upgradable packages for a prompt status.
* A simple Upgrade-All command line script that would be fast to start and to complete.

**Comment by ethanbergstrom** [comment]
I was partial to the `-Upgradable` switch myself, but Crescendo doesn't really work that way, so `Get-WinGetPackageUpdate` it is. 

Please upgrade to v0.3.0 of the module, though please note that due to [a bug in winget-cli 1.2 and below](https://github.com/microsoft/winget-cli/issues/1869), you need to have previously agreed to the package source licenses, otherwise the cmdlet will hang indefinitely.

**Comment by Lockszmith-GH** [comment]
I'm guessing it is hanging because it is waiting for input from the standard input.
What would happen if you send "n`n" into stdin ?

Or maybe this might provide some help with the hanging issue?
https://github.com/microsoft/winget-cli/discussions/1536#discussioncomment-1414887

Never the less, thank you for implementing this, I'll be testing soon.

**Comment by Lockszmith-GH** [comment]
Tested, and it works as expected. Again, thank you so much for adding this feature.
