### ISSUE TITLE
Get-WinGetPackageUpdate throws startIndex cannot be larger than length of string

### ISSUE THREAD

**Issue by sibbl** [ethanbergstrom/Cobalt#12]
Thanks for implementing `Get-WinGetPackageUpdate`!

Unfortunately it throws an error on my machine with German localization. Please find the output of `winget upgrade` attached: [output.txt](https://github.com/ethanbergstrom/Cobalt/files/8685293/output.txt)

The error itself unfortunately doesn't contain much information like a line where it happened: 

```
MethodInvocationException: Exception calling "Substring" with "2" argument(s): "startIndex cannot be larger than length of string. (Parameter 'startIndex')"
```

I could imagine that it's due to `Aktualisierungen verfügbar.` (`upgrades available.` in German) being a localized value.

Thank you very much in advance!

**Comment by ethanbergstrom** [comment]
Ugh...very likely. Sorry about that, I completely forgot about localization for those strings. I'll dig through the localization resources to see what I can tease out to strip the report information from the bottom of the output.

**Comment by ethanbergstrom** [comment]
@sibbl I don't have an easy means of testing this myself, but I think v0.3.1 should fix the issue you're seeing.

Please test it out when you have a moment and let me know if it's working now.

**Comment by sibbl** [comment]
@ethanbergstrom just downloaded version 3.1 and can confirm it's working. Thanks for the quick fix and enjoy your weekend!
