### ISSUE TITLE
Get-WinGetPackageUpdate outputs incorrect package Id

### ISSUE THREAD

**Issue by phikaczu** [ethanbergstrom/Cobalt#16]
Thank you for making winget more useful in PowerShell!

Cobalt version 0.3.1

The Id for package `Microsoft.DotNet.DesktopRuntime.6` is incorrect. The output from `winget upgrade` is
```powershell
Name                                            Id                                Version          Available     Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Windows Desktop Runtime - 5.0.17 (x6… Microsoft.DotNet.DesktopRuntime.6 < 6.0.5          6.0.13        winget
```
but the output from `Get-WinGetPackageUpdate` is
```powershell
ID                               Version       Available     Source
--                               -------       ---------     ------
Microsoft.DotNet.DesktopRuntime. 66.0.5        6.0.13        winget
```

**Comment by ethanbergstrom** [comment]
Unfortunately, Winget is pretty awful at cleanly and consistently truncating columnar output - see https://stackoverflow.com/questions/70012084/powershell-encoding-issue-when-storing-cmdlet-response-in-variable that describes the issue well. 

I had originally tried to work around this problem in non-UTF-8 terminals with [this change](https://github.com/ethanbergstrom/Cobalt/compare/v0.0.3...v0.0.4#diff-636b1afc3b38a48189f3f4af165ac62dd4a39d442528b9c7b2209cfb1fa620f7R162) way back in v0.0.4, but it looks like my regex wasn't quite right. 

I made [a small tweak](https://github.com/ethanbergstrom/Cobalt/compare/v0.3.1...v0.3.2#diff-636b1afc3b38a48189f3f4af165ac62dd4a39d442528b9c7b2209cfb1fa620f7R73) to the regex in v0.3.2, which is out now on PSGallery and should fix this issue for you. 

Before:
```
PS C:\Users\ethan> Get-WinGetPackageUpdate | Where-Object ID -like Microsoft.VCRedist.2015*

ID                          Version       Available     Source
--                          -------       ---------     ------
Microsoft.VCRedist.2015+.x6 414.31.31103. 014.34.31931. winget
Microsoft.VCRedist.2015+.x8 614.31.31103. 014.34.31931. winget
```

After:
```
PS C:\Users\ethan> Get-WinGetPackageUpdate | Where-Object ID -like Microsoft.VCRedist.2015*

ID                           Version       Available     Source
--                           -------       ---------     ------
Microsoft.VCRedist.2015+.x64 14.31.31103.0 14.34.31931.0 winget
Microsoft.VCRedist.2015+.x86 14.31.31103.0 14.34.31931.0 winget
```
