### ISSUE TITLE
Install-WinGetPackage local package newer than repo package causes Cobalt error

### ISSUE THREAD

**Issue by Kizan** [ethanbergstrom/Cobalt#4]
Ran into an odd situation using Install-WinGetPackage. I was trying to install Microsoft.OneDrive. The current Winget Repo has an older version than what is installed on my test box. This threw an error in Cobalt as shown below.

I have Microsoft.OneDrive v21.245.1128.0002 installed but the repo version is v21.230.1107.0004

I can hide the message by using -ErrorAction:SilentlyContinue but figured someone would want to know about the issue.

Cobalt\0.0.10\Cobalt.psm1:320 char:13

```
                        param ($output)
                        if ($output) {
                            if ($output -match 'failed') {
                                Write-Error ($output -join "`r`n")
                            } else {
                                $output | ForEach-Object {
                                    if ($_ -match '\[(?<id>[\S]+)\] Version (?<version>[\S]+)' -and $Matches.id -and
$Matches.version) {
                                            [pscustomobject]@{
                                                ID = $Matches.id
                                                Version = $Matches.version
                                            }
                                    }
                                }
                            }
                        }
                      :
Found Microsoft OneDrive [Microsoft.OneDrive] Version 21.230.1107.0004
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://oneclient.sfx.ms/Win/Prod/21.230.1107.0004/amd64/OneDriveSetup.exe

  ΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆ  0.00 B / 46.5 MB
  ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆ  27.5 MB / 46.5 MB
  ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûê  46.5 MB / 46.5 MB
Successfully verified installer hash
Starting package install...

Installer failed with exit code: 2147747474
A higher version of this application is already installed.
At C:\Program Files\WindowsPowerShell\Modules\Cobalt\0.0.10\Cobalt.psm1:320 char:13
+             & $__handler $result
+             ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
```

**Comment by ethanbergstrom** [comment]
Do you get the same error when just using 'winget' without the Cobalt?

My guess is that's a WinGet issue, not a Cobalt issue.

**Comment by Kizan** [comment]
I do get an message from WinGet.exe that says "newer already version installed". I thought Cobalt would parse that message instead of throw a powershell error message.

**Comment by ethanbergstrom** [comment]
What would the expected output be, in the event of a package installation failure, other than to throw a PowerShell error?

**Comment by Kizan** [comment]
It'd be great if the code caught the error and let me display a message to the user rather than a long-ish powershell error. Winget does output a line indicating that the local version is higher than the version in the repo.

**Comment by ethanbergstrom** [comment]
Which part of the error is too verbose?

This part:
```Found Microsoft OneDrive [Microsoft.OneDrive] Version 21.230.1107.0004
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://oneclient.sfx.ms/Win/Prod/21.230.1107.0004/amd64/OneDriveSetup.exe

  ΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆ  0.00 B / 46.5 MB
  ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆΓûÆ  27.5 MB / 46.5 MB
  ΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûêΓûê  46.5 MB / 46.5 MB
Successfully verified installer hash
Starting package install...
```

Or this part:
```
At C:\Program Files\WindowsPowerShell\Modules\Cobalt\0.0.10\Cobalt.psm1:320 char:13
+             & $__handler $result
+             ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
```

**Comment by Kizan** [comment]
The Winget.exe is just a line or two. If you aren't interested I was just putting forth a suggestion.

**Comment by Kizan** [comment]
FYI the message from Winget.exe is:

"A higher version of this application is already installed."

Looks like sometimes there's an error code returned too. Not always the same, but 1603 is the most common.

**Comment by ethanbergstrom** [comment]
The block of PowerShell code that shows up in the output is an artifact of PowerShell 5.1 - that's just how it reports errors. 

I have made a small edit in the PR I'm linking which will take some of the extra verbosity out of the message and only show what matches or comes after the keyword 'failed', but I don't think it will solve the overall concern. 

If you want more concise errors, I recommend switching to PowerShell 7.
